/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(sampling_synchronization.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(c8bb79ae5be873e8364ff176c2a43efe)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/tempest/sampling_synchronization.h>
// pydoc.h is automatically generated in the build directory
#include <sampling_synchronization_pydoc.h>

void bind_sampling_synchronization(py::module& m)
{

    using sampling_synchronization    = ::gr::tempest::sampling_synchronization;


    py::class_<sampling_synchronization, gr::block, gr::basic_block,
        std::shared_ptr<sampling_synchronization>>(m, "sampling_synchronization", D(sampling_synchronization))

        .def(py::init(&sampling_synchronization::make),
           py::arg("Htotal"),
           py::arg("manual_correction"),
           D(sampling_synchronization,make)
        )
        




        
        .def("set_Htotal",&sampling_synchronization::set_Htotal,       
            py::arg("Htotal"),
            D(sampling_synchronization,set_Htotal)
        )


        
        .def("set_manual_correction",&sampling_synchronization::set_manual_correction,       
            py::arg("correction"),
            D(sampling_synchronization,set_manual_correction)
        )

        ;




}








