/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(ssamp_correction.h) */
/* BINDTOOL_HEADER_FILE_HASH(7eca001429a7aeb2a9617d987166861c) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/tempest/ssamp_correction.h>
// pydoc.h is automatically generated in the build directory
#include <ssamp_correction_pydoc.h>

void bind_ssamp_correction(py::module &m) {

  using ssamp_correction = ::gr::tempest::ssamp_correction;

  py::class_<ssamp_correction, gr::block, gr::basic_block,
             std::shared_ptr<ssamp_correction>>(m, "ssamp_correction",
                                                D(ssamp_correction))

      .def(py::init(&ssamp_correction::make), py::arg("Htotal"),
           py::arg("Vtotal"), py::arg("correct_sampling"),
           py::arg("max_deviation"), D(ssamp_correction, make))

      .def("set_Htotal_Vtotal", &ssamp_correction::set_Htotal_Vtotal,
           py::arg("Htotal"), py::arg("Vtotal"),
           D(ssamp_correction, set_Htotal_Vtotal))

      ;
}
